name: "Free Disk Space"
description: "Free Disk Space"
icon: "archive"
color: "green"

runs:
  using: "composite"
  steps:

    - shell: bash
      env:
        LINE: =====================
      run: |
        echo "${LINE} Before ${LINE}"
        df -h /
        echo "${LINE}${LINE}${LINE}"

        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc

        echo "${LINE} After ${LINE}"
        df -h /
        echo "${LINE}${LINE}${LINE}"
