name: "Free Disk Space"
description: "Free Disk Space"
icon: "archive"
color: "green"

runs:
  using: "composite"
  steps:

    - shell: bash
      run: |
        df -h 
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        df -h
